name: Test
on:
  push:
  workflow_dispatch:

jobs:
  lint-python:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.9

      - id: lint
        name: Lint Python code
        run: pipenv run flake8 ./ --verbose

  mypy-python:
    name: Static type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.9

      - id: mypy
        name: Run mypy
        run: pipenv run mypy ./ --ignore-missing-imports

  test-python:
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: ${{ matrix.python }}

      - id: tests
        name: Run tests
        run: make test
